django_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products.views import products


app_name = 'products'

urlpatterns = [
    path('', products, name='index')
]

users/urls.py
from django.urls import path
from users.views import login, registration, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('registration/', registration, name='registration'),
    path('logout/', logout, name='logout')
]

products/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products_images', blank=True, null=True)
    description = models.CharField(max_length=256)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=1)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'Продукт: {self.name} | Категория: {self.category.name}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', null=True, blank=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Введите имя пользователя', 'class': 'form-control py-4'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Введите пароль', 'class': 'form-control py-4'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите адрес эл. почты'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите фамилию'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

products/views.py
from django.shortcuts import render
from products.models import Product, ProductCategory


def index(requests):
    context = {'title': 'PatriotStore'}
    return render(requests, 'products/index.html', context)


def products(requests):
    context = {
                'title': 'Products',
                'products': Product.objects.all(),
                'categories': ProductCategory.objects.all()
    }
    return render(requests, 'products/product.html', context)

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse
from django.contrib import messages

from users.forms import UserLoginForm, UserRegistrationForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))
    else:
        form = UserLoginForm()
    context = {'title': 'PatriotStore - Авторизация', 'form': form}
    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Поздравляем! Регистрация прошла успешно.')
            return HttpResponseRedirect(reverse('users:login'))
    else:
        form = UserRegistrationForm()
    context = {'title': 'PatriotStore - Регистрация', 'form': form}
    return render(request, 'users/registration.html', context)


def logout(requests):
    auth.logout(requests)
    return HttpResponseRedirect(reverse('index'))

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/reg_aut/auth-admin.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content %} {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/reg_aut/auth-admin.js' %}"></script>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}
{% block content %}
    <div class="col-lg-5">
        {% if messages or form.errors %}
            <div class="alert
            {% if messages %} alert-success {% else %} alert-warning {% endif %}
            alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% else %}
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'users:login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                        {{ form.password }}
                    </div>
                    <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                        <a class="small" href="#">Забыли пароль?</a>
                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small"><a href="{% url 'users:registration' %}">Нужен аккаунт? Зарегистрируйся!</a></div>


                <button class="btn btn-round form-control">
                    <a href="#">
{#                        {% url 'social:begin' 'vk-oauth2' %}?next='/#}
                войти через VK
                    </a>
                </button>

            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/registration.html
{% extends 'users/base.html' %}

{% block content %}
    <div class="col-lg-7">
        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert"
                 style="margin-top: 50px;">
                {{ form.errors|escape }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
            </div>
            <div class="card-body">
                <form action="{% url 'users:registration' %}" method="post">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6">
                            <label class="small mb-1" for="inputUsername">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                {{ form.password1 }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                    пароля</label>
                                {{ form.password2 }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group mt-4 mb-0">
                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small"><a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
            </div>
        </div>
    </div>
{% endblock %}